// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/pin-pon.proto

package go_protocol_buffer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PinPonServiceClient is the client API for PinPonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinPonServiceClient interface {
	Send(ctx context.Context, in *PinPonRequest, opts ...grpc.CallOption) (*PinPonResponse, error)
}

type pinPonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPinPonServiceClient(cc grpc.ClientConnInterface) PinPonServiceClient {
	return &pinPonServiceClient{cc}
}

func (c *pinPonServiceClient) Send(ctx context.Context, in *PinPonRequest, opts ...grpc.CallOption) (*PinPonResponse, error) {
	out := new(PinPonResponse)
	err := c.cc.Invoke(ctx, "/PinPon.PinPonService/send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PinPonServiceServer is the server API for PinPonService service.
// All implementations must embed UnimplementedPinPonServiceServer
// for forward compatibility
type PinPonServiceServer interface {
	Send(context.Context, *PinPonRequest) (*PinPonResponse, error)
	mustEmbedUnimplementedPinPonServiceServer()
}

// UnimplementedPinPonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPinPonServiceServer struct {
}

func (UnimplementedPinPonServiceServer) Send(context.Context, *PinPonRequest) (*PinPonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedPinPonServiceServer) mustEmbedUnimplementedPinPonServiceServer() {}

// UnsafePinPonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinPonServiceServer will
// result in compilation errors.
type UnsafePinPonServiceServer interface {
	mustEmbedUnimplementedPinPonServiceServer()
}

func RegisterPinPonServiceServer(s grpc.ServiceRegistrar, srv PinPonServiceServer) {
	s.RegisterService(&PinPonService_ServiceDesc, srv)
}

func _PinPonService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinPonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinPonServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PinPon.PinPonService/send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinPonServiceServer).Send(ctx, req.(*PinPonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PinPonService_ServiceDesc is the grpc.ServiceDesc for PinPonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinPonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PinPon.PinPonService",
	HandlerType: (*PinPonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "send",
			Handler:    _PinPonService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pin-pon.proto",
}
